bt/bt/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from user.views import login

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('user.urls')),
    path('project/', include('project.urls')),
    path('',login),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bt/project/urls.py
from django.contrib import admin
from django.urls import path
from .views import *

urlpatterns = [
    path('projectcreate/', ProjectCreateView.as_view(), name='projectcreate'),
    path('projectlist/', ProjectListView.as_view(), name='projectlist'),
    path('projectteamcreate/', ProjectTeamCreateView.as_view(), name='projectteamcreate'),
    path('projectteamlist/', ProjectTeamListView.as_view(), name='projectteamlist'),
    path('projectteamdetail/',ProjectTeamDetailView.as_view(),name='projectteamdetail'),
    path('projectteamdelete/',ProjectTeamDeleteView.as_view(), name='projectteamdelete'),
    path('projectteamupdate/', ProjectTeamUpdateView.as_view(), name='projectteamupdate'),
    path('projectupdate/<int:pk>', ProjectUpdateView.as_view(), name='projectupdate'),
    path('projectdetail/<int:pk>', ProjectDetailView.as_view(), name='projectdetail'),
    path('projectdelete/<int:pk>', ProjectDeleteView.as_view(), name='projectdelete'),
    path('createprojectmodule/',CreateProjectModule.as_view(),name='createprojectmodule'),
    path('listprojectmodule/',ProjectModuleListByProject.as_view(),name='listprojectmodule'),
    path('detailprojectmodule/<int:pk>', ProjectDetailView.as_view(), name='detailprojectmodule'),
    path('create_project_task/',CreateProjectTask.as_view(),name='create_project_task'),
    path('project_task_list/',ProjectTaskListByProject.as_view(),name='project_task_list'),
    path('project_task_delete/<int:pk>',ProjectTaskDeleteView.as_view(),name='project_task_delete'),
    path('project_task_update/<int:pk>',ProjectTaskUpdateView.as_view(),name='project_task_update'),
    path('project_task_detail/<int:pk>',ProjectTaskDetailView.as_view(),name='project_task_detail'),
    path('project_task_assign/<int:pk>',ProjectTaskView.as_view(),name='project_task_assign'),
]

bt/project/models.py
from django.db import models
# from django.contrib.auth.models import AbstractUser
from user.models import User

class Project(models.Model):
    title = models.CharField(max_length=30, null=False)
    description = models.CharField(max_length=500)
    technology = models.CharField(max_length=100)
    estimatedHours = models.PositiveIntegerField()
    startDate = models.DateField()
    completionDate = models.DateField()

    createdtime = models.DateTimeField(auto_now_add=True)
    updatedtime = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    class Meta:
        db_table = 'Project'

class ProjectTeam(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    createdtime = models.DateTimeField(auto_now_add=True)
    updatedtime = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = 'Project_team'

class Status(models.Model):
    statusName = models.CharField(max_length=20, null=False, unique=True)

    createdtime = models.DateTimeField(auto_now_add=True)
    updatedtime = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.statusName

    class Meta:
        db_table = 'status'

class ProjectModule(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    moduleName = models.CharField(max_length=30, null=False)
    description = models.CharField(max_length=30)
    estimatedHours = models.PositiveIntegerField()
    status = models.ForeignKey(Status, on_delete=models.CASCADE)
    startDate = models.DateField(null=True)
    endedDate = models.DateField(null=True)

    createdtime = models.DateTimeField(auto_now_add=True)
    updatedtime = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.moduleName

    class Meta:
        db_table = 'Project_module'

priorityChoice =  (("High" ,"High") ,("Low" ,"Low") ,("Normal" ,"Normal"))

class Task(models.Model):
    module = models.ForeignKey(ProjectModule, on_delete=models.CASCADE)
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    title = models.CharField(max_length=50)
    priority = models.CharField(choices=priorityChoice ,max_length=30)
    description = models.CharField(max_length=500, null=False)
    status = models.ForeignKey(Status, on_delete=models.CASCADE)
    totalMinutes = models.PositiveIntegerField()

    createdtime = models.DateTimeField(auto_now_add=True)
    updatedtime = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    class Meta:
        db_table = 'task'

class UserTask(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    task = models.ForeignKey(Task, on_delete=models.CASCADE)

    class Meta:
        db_table = 'user_task'


# class ProjectModule(models.Model):
#      project = models.ForeignKey(Project, on_delete=models.CASCADE)
#      moduleName = models.CharField(max_length=100)
#      description = models.TextField()
#      estimeted_hours = models.IntegerField()
#      status = models.CharField(max_length=100)
#      startDate = models.DateField()
#      created_at = models.DateTimeField(auto_now_add=True)
#      updated_at = models.DateTimeField(auto_now=True)
    
#      class Meta:
#          db_table = 'project_module'
    
#      def __str__(self):
#          return self.moduleName

bt/project/forms.py
from django import forms
from django.db import transaction
from .models import Project,ProjectTeam ,ProjectModule ,Task
from user.models import User

class ProjectCreationForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = '__all__'

        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Project Title'}),
            'description': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Project Description'}),
            'technology': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Project Technology'}),
            'estimatedHours': forms.NumberInput(attrs={'class': 'form-control', 'placeholder': '12'}),
            'startDate': forms.DateInput(attrs={'class': 'form-control datepicker', 'placeholder': 'DD/MM/YYYY'}),
            'completionDate': forms.DateInput(attrs={'class': 'form-control datepicker', 'placeholder': 'DD/MM/YYYY'})
        }

    @transaction.atomic
    def save(self):
        project = super().save(commit=False)
        project.save()
        return project

class ProjectTeamCreationForm(forms.ModelForm):
    user = forms.ModelChoiceField(queryset=User.objects.filter(is_developer=True))

    class Meta:
        model = ProjectTeam
        fields = '__all__'
        
        # widgets = {
        #     'project': forms.ChoiceField(attrs={'class': 'form-control'}),
        #     'user': forms.SelectMultiple(attrs={'class': 'form-control'})
        # }

    @transaction.atomic
    def save(self):
        projectteam = super().save(commit=False)
        projectteam.save()
        return projectteam

class CreateProjectModuleForm(forms.ModelForm):
     class Meta:
        model = ProjectModule
        fields = '__all__'      

class CreateProjectTaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = '__all__' 

bt/project/views.py
from django.shortcuts import render, redirect
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView
from .forms import *
from .models import *

# Create your views here.
class ProjectCreateView(CreateView):
    model = Project
    form_class = ProjectCreationForm
    template_name = 'project/project_create.html'
    success_url = '/project/projectlist'

    def form_valid(self, form):
        return super().form_valid(form)
    
class ProjectListView(ListView):
    model = Project
    template_name = 'project/project_list.html'
    context_object_name = 'projectlist'

    def get_queryset(self):
        return super().get_queryset()

class ProjectUpdateView(UpdateView):
    model = Project
    form_class = ProjectCreationForm
    template_name = 'project/project_create.html'
    success_url = '/project/projectlist'

class ProjectDetailView(DetailView):
    model = Project
    template_name = 'project/project_detail.html'
    context_object_name = 'projectdetail'

    def get(self, request, *args, **kwargs):
        team = ProjectTeam.objects.filter(project_id = self.kwargs['pk'])
        return render(request, self.template_name, {'projectdetail': self.get_object(), 'team':team})
    
class ProjectDeleteView(DeleteView):
    model = Project
    template_name = 'project/project_delete.html'
    success_url = '/project/projectlist'
    context_object_name = 'projectdelete'

    # def get(self, request, *args, **kwargs):
    #     return self.delete(request, *args, **kwargs)
    
    # success_url = 'project/projectlist'
    
class ProjectTeamCreateView(CreateView):
    model = ProjectTeam
    form_class = ProjectTeamCreationForm
    template_name = 'project/projectteam_create.html'
    success_url = '/project/projectteamlist'

    def form_valid(self, form):
        return super().form_valid(form)
    
class ProjectTeamListView(ListView):
    model = ProjectTeam
    template_name = 'project/projectteam_list.html'
    # success_url = '/project/projectteam_list'
    context_object_name = 'projectteamlist'

    def get_queryset(self):
        return super().get_queryset()
    
class ProjectTeamUpdateView(UpdateView):
     model = ProjectTeam
     form_class = ProjectTeamCreationForm
     template_name = 'project/projectteam_create.html'
     success_url = '/project/projectteamcreate'
     
    
class ProjectTeamDetailView(ListView):
    model = ProjectTeam
    template_name = 'projectteam/projectteam_detail.html'
    context_object_name = 'projectteamdetail'
    

    def get(self, request, *args, **kwargs):
        team = ProjectTeam.objects.filter(project_id = self.kwargs['pk'])
        return render(request, self.template_name, {'projectteamdetail': self.get_object(), 'team':team})
    #  def get_queryset(self):
    #      return super().get_queryset()

class ProjectTeamDeleteView(DeleteView):
    model = ProjectTeam
    template_name = 'project/projectteam_delete.html'
    success_url = '/project/projectteamdelete'
    context_object_name = 'projectteamdelete'
    
    def get(self, request, *args, **kwargs):
        team = ProjectTeam.objects.filter(project_id = self.kwargs['pk'])
        return render(request, self.template_name, {'projectteamdelete': self.get_object(), 'team':team})



    
class CreateProjectModule(CreateView):
    model = ProjectModule
    form_class = CreateProjectModuleForm
    template_name = 'project/create_project_module.html'
    success_url = '/project/listprojectmodule/'

    def form_valid(self, form):
        user = form.save()
        return redirect('listprojectmodule')
        

class ProjectModuleListByProject(ListView):
    model = ProjectModule
    template_name = 'project/list_project_module.html'
    success_url = '/project/listprojectmodule'
    context_object_name = 'listprojectmodule'
    
class ProjectModuleDetailView(DetailView):
    model = ProjectModule
    template_name = 'project/detail_project_module.html'
    # success_url = '/project/detailprojectmodule'
    context_object_name = 'detailprojectmodule'

    def get(self, request, *args, **kwargs):
         team = ProjectTeam.objects.filter(project_id = self.kwargs['pk'])
         return render(request, self.template_name, {'detailprojectmodule': self.get_object(), 'team':team})
    
    # def get_queryset(self):
    #     return super().get_queryset().filter(project_id=self.kwargs['pk'])


class CreateProjectTask(CreateView):
    model = Task
    form_class = CreateProjectTaskForm
    template_name = 'project/create_project_task.html'
    success_url = '/project/project_task_list/'

class ProjectTaskListByProject(ListView):
    model = Task
    template_name = 'project/project_task_list.html'
    context_object_name = 'project_task_list'

class ProjectTaskDetailView(DetailView):
    model = Task
    template_name = 'project/project_task_detail.html'
    context_object_name = 'project_task_detail'

    def get(self, request, *args, **kwargs):
        team = ProjectTeam.objects.filter(project_id = self.kwargs['pk'])
        return render(request, self.template_name, {'project_task_detail': self.get_object(), 'team':team})


# class TaskUpdateView(UpdateView):
#     model = Task
#     form_class = CreateProjectModuleForm
#     template_name = 'project/project_task_create.html'
#     success_url = '/project/project_task_list/' 
    
class ProjectTaskDeleteView(DeleteView):
    model = Task
    template_name = 'project/project_task_delete.html'
    success_url = '/project/project_task_list'
    context_object_name = 'project_task_delete'

class ProjectTaskUpdateView(UpdateView):
    model = Task
    form_class = CreateProjectTaskForm
    template_name = 'project/create_project_task.html'
    success_url = '/project/project_task_list'

    # def form_valid(self, form):
    #     return super().form_valid(form)

class ProjectTaskView(UpdateView):
    model = Task
    form_class = CreateProjectTaskForm
    template_name = 'project/assign_task.html'
    success_url = '/project/project_task_list'
    
    # def form_valid(self, form):
    #     return super().form_valid(form)

bt/templates/project/assign_task.html
{% extends 'layouts/base.html' %}
{% load static %}

{% load crispy_forms_tags %}

{% block content %}

<!-- Page content -->
<div class="container-fluid mt--12 pt-5">
  <div class="row">
    <div class="col-xl-12 order-xl-1">
      <div class="card">
        <div class="card-header">
          <div class="row align-items-center">
            <div class="col-8">
              <h3 class="mb-0">Assign Developer </h3>
            </div>
            <div class="col-4 text-right">
              <a href="#!" class="btn btn-sm btn-primary">Assign Developer</a>
            </div>
            <div class="col-4 text-right">
            {% comment %} <a href="{% url 'project_task_list' %}" class="btn btn-sm btn-primary">View Project Task</a>  {% endcomment %}
            <a href="{% url 'project_task_list' %}" class="btn btn-sm btn-primary">View Project Task List</a>
            </div>
          </div>
        </div>
        <div class="card-body">
          <form method="POST">
            {% csrf_token %}
            <h6 class="heading-small text-muted mb-4">Project Task information</h6>
            <div class="pl-lg-4">
              <div class="row">
                <div class="col-lg-12">
                  <div class="form-group">
                    <label class="form-control-label" >Project Task</label>
                    {{ form.project}}
                     {% comment %} <input type="text" id="input-username" class="form-control" placeholder="Username" value="{{ request.project}}"> {% endcomment %}
                   </div>
                </div>
                
                {% comment %} <div class="col-lg-12">
                  <div class="form-group">
                    <label class="form-control-label">Developer</label>
                    {{ form.user }} {% endcomment %}
                     {% comment %} <input type="text" id="input-username" class="form-control" placeholder="Username" value="{{ request.user.username }}"> {% endcomment %}
                     <div class="row">
                        <div class="col-lg-12">
                          <div class="form-group">
                            <label class="form-control-label" >Developer</label>
                            
                            <select name="user" required id="id_user">
                            <option value="" selected>---------</option>

                            <option value="3">mokshd1</option>

                            <option value="4">testert1</option>

                            <option value="2">mokshm1</option>

                            <option value="1"></option>

                            </select>
                    </div>
                </div>
                
              </div>
              <div class="col-lg-4">
                <div class="form-group">
                <input type="submit" id="input-postal-code" class="btn btn-primary" value="Assign">
                {% comment %} <input type="submit" id="input-postal-code" class="btn btn-primary" value="Assign">     {% endcomment %}
            </div>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div> 

 {% include "includes/footer.html" %}

</div>

{% endblock content %}

<!-- Specific JS goes HERE --> 
{% block javascripts %}
<script src="{% static '/assets/vendor/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js' %}"></script>
{% endblock javascripts %}

bt/templates/project/create_project_module.html
{% extends 'layouts/base.html' %}
{% load static %}

{% block title %} Create Project Module{% endblock title %}

{% block content %}

<!-- Page content -->
<div class="container-fluid mt--12 pt-5">
  <div class="row">
    <div class="col-xl-12 order-xl-1">
      <div class="card">
        <div class="card-header">
          <div class="row align-items-center">
            <div class="col-8">
              {% if request.path == '/project/create_project_module/' %}
              <h3 class="mb-0">Create Project Module</h3>
              {% else %}
              <h3 class="mb-0">Add Project Module</h3>
              {% endif %}
            </div>
             {% comment %} <a href="{% url 'list_project_module' %}" class="btn btn-sm btn-primary"> Back</a> {% endcomment %}
             
              
                <div class="header-body">
                  <a href="{% url 'listprojectmodule' %}" class="btn btn-warning mt-2"><i class="ni ni-bold-left mr-2"></i> Back</a>
                  
            </div>
          </div>
        </div>
        <div class="card-body">
          <form method = "post">
            {% csrf_token %}
            {{form.as_p}}
            {% comment %} <input type = "submit" value = "submit"> {% endcomment %}
          {% comment %} </form>  {% endcomment %}
           {% comment %} <form method="POST">
            {% csrf_token %}
            <h6 class="heading-small text-muted mb-4">Project Module information</h6>
            <div class="pl-lg-4">
              <div class="row">
                <div class="col-lg-12">
                  <div class="form-group">
                    <label class="form-control-label" for="input-username">Project</label>
                    {{ form.project }}
                     <input type="text" id="input-username" class="form-control" placeholder="Username" value="{{ request.user.username }}">
                   </div>
                </div>
                <div class="col-lg-12">
                  <div class="form-group">
                    <label class="form-control-label">Module Name</label>
                    {{ form.moduleName }}
                <div class="col-lg-12">
                  <div class="form-group">
                    <label class="form-control-label">Description</label>
                    {{ form.description }} 
                    {% comment %} <textarea rows="4" class="form-control" placeholder="A few words about you ...">A beautiful Dashboard for Bootstrap 4. It is Free and Open Source.</textarea> {% endcomment %}
                  </div>
                </div>
                {% comment %} <div class="col-lg-12">
                  <div class="form-group">
                    <label class="form-control-label" for="input-username">Technology</label>
                    {{ form.technology }}
                    {% comment %} <input type="text" id="input-username" class="form-control" placeholder="Username" value="{{ request.user.username }}"> {% endcomment %}
                  {% comment %} </div>
                </div>  {% endcomment %}
                 {% comment %} <div class="col-lg-4">
                  <div class="form-group">
                    <label class="form-control-label" for="input-city">Estimated Hours</label>
                    {{ form.estimatedHours }}
                     <input type="text"  class="form-control" >
                   </div>
                </div>
                <div class="col-lg-4">
                  <div class="form-group">
                    <label class="form-control-label" for="input-city">Start Date</label>
                    {{ form.startDate }}
                     <input type="text" id="input-country" class="form-control" placeholder="Country" value="">
                   </div>
                </div>
                <div class="col-lg-4">
                  <div class="form-group">
                    <label class="form-control-label" for="input-city">Ended Date</label>
                    {{ form.endedDate }} 
                     <input type="number" id="input-postal-code" class="form-control" placeholder="Postal code">
                  </div>
                </div>
              </div>
              <div class="col-lg-4">
                <div class="form-group">
                  <label class="form-control-label" for="input-city">Status</label>
                  {{ form.status }} 
                   <input type="number" id="input-postal-code" class="form-control" placeholder="Postal code">
                </div>
              </div>
            </div> {% endcomment %}
              {% comment %} <div class="col-lg-4">
                <div class="form-group">
                  <label class="form-control-label" for="input-city">createdtime</label>
                  {{ form.createdtime }}
                </div>
              </div>
            </div>
            <div class="col-lg-4">
              <div class="form-group">
                <label class="form-control-label" for="input-city">updatedtime</label>
                {{ form.updatetime }}
              </div>
            </div>
          </div> {% endcomment %}
              {% if request.path == '/project/create_project_module.html' %}
              <div class="col-lg-12">
                <div class="form-group">
                    <input type="submit" id="input-postal-code" class="btn btn-primary float-right btn-lg btn-block" value="Create">
                  </div>
                </div>
                    {% else %}
                    <div class="row">
                      <div class="col-lg-6">
                        <div class="form-group">
                          <a href="{% url 'index' %}" class="btn btn-light float-right btn-lg btn-block">Close</a>
                        </div>
                      </div>
                      <div class="col-lg-6">
                        <div class="form-group">
                          <input type="submit" a href="{% url 'listprojectmodule' %}" class="btn btn-primary float-right btn-lg btn-block" value="Add">
                        </div>
                      </div>
                    </div>
                  {% endif %}
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>

  {% include "includes/footer.html" %}

</div>

{% endblock content %}

<!-- Specific JS goes HERE --> 
{% block javascripts %}
<script src="{% static '/assets/vendor/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js' %}"></script>
{% endblock javascripts %} 

bt/templates/project/detail_project_module.html
{% extends 'layouts/base.html' %}
{% load static %}

{% block title %} Project Module Detail {% endblock title %}

{% block content %}
<!-- Header -->
<div class="header bg-primary pb-6">
    <div class="container-fluid">
      <div class="header-body">
        <a href="{% url 'listprojectmodule' %}" class="btn btn-warning mt-2"><i class="ni ni-bold-left mr-2"></i> Back</a>
        <!-- Card stats -->
        <div class="row pt-2">
            <div class="col-xl-3 col-md-6">
              <div class="card card-stats">
                <!-- Card body -->
                <div class="card-body">
                  <div class="row">
                    <div class="col">
                        <h5 class="card-title text-uppercase text-muted mb-1">Project Module status</h5>
                        <span class="h2 font-weight-bold mb-0 badge badge-dot mr-4">
                            <i class="bg-warning"></i> Active
                        </span>
                        
                        <div class="progress-wrapper">
                            <div class="progress-info">
                              <div class="progress-label">
                                <span>Task completed</span>
                              </div>
                              <div class="progress-percentage">
                                <span>90%</span>
                              </div>
                            </div>
                            <div class="progress">
                              <div class="progress-bar bg-warning" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 60%;"></div>
                            </div>
                          </div>
                    </div>
                    
                  </div>
                  <p class="mt-3 mb-0 text-sm">
                    <span class="text-nowrap font-weight-bold mr-1">Since</span>
                    <span class="text-nowrap text-success font-weight-bold"> {{ detailprojectmodule.startDate }} </span>
                  </p>
                </div>
              </div>
            </div>
            <div class="col-xl-5 col-md-6">
              <div class="card card-stats">
                <!-- Card body -->
                <div class="card-body">
                  <div class="row">
                    <div class="col">
                      <h5 class="card-title text-uppercase text-muted mb-0">Project Module information</h5>
                      {% comment %} <span class="h2 font-weight-bold mb-0">2,356</span> {% endcomment %}
                    </div>
                    <div class="col-auto">
                      <div class="icon icon-shape bg-gradient-orange text-white rounded-circle shadow">
                        <i class="ni ni-collection"></i>
                      </div>
                    </div>
                  </div>
                  <p class="mt-3 mb-0 text-sm">
                    <span class="text-nowrap font-weight-bold mr-1">Title : </span>
                    <span class="text-nowrap text-success font-weight-bold"> {{ detailprojectmodule.title }} </span>
                  </p>
                  <p class="mt-3 mb-0 text-sm">
                    <span class="text-nowrap font-weight-bold mr-1">Description : </span>
                    <span class="text-nowrap text-success font-weight-bold"> {{ detailprojectmodule.description }} </span>
                  </p>
                  {% comment %} <p class="mt-3 mb-0 text-sm">
                    <span class="text-nowrap font-weight-bold mr-1">Technology : </span>
                    <span class="text-nowrap text-success font-weight-bold"> {{ projectdetail.technology }} </span>
                  </p> {% endcomment %}
                  <p class="mt-3 mb-0 text-sm">
                    <span class="text-nowrap font-weight-bold mr-1">Estimated Hours : </span>
                    <span class="text-nowrap text-success font-weight-bold"> {{ detailprojectmodule.estimatedHours }} </span>
                  </p>
                  <p class="mt-3 mb-0 text-sm">
                    <span class="text-nowrap font-weight-bold mr-1">Start Date : </span>
                    <span class="text-nowrap text-success font-weight-bold"> {{ detailprojectmodule.startDate }} </span>
                  </p>
                  <p class="mt-3 mb-0 text-sm">
                    <span class="text-nowrap font-weight-bold mr-1">Ended Date : </span>
                    <span class="text-nowrap text-success font-weight-bold"> {{ detailprojectmodule.endedDate }} </span>
                  </p>
                </div>
                <div class="ms-auto text-end d-flex flex-row-reverse">
                  {% comment %} <a class="btn btn-link text-danger text-gradient px-3 mb-0" href="{% url 'projectdelete' detailprojectmodule.id %}"><i class="fas fa-trash mr-2"></i>Delete</a> {% endcomment %}
                  <a class="btn btn-link text-dark px-3 mb-0" href="{% url 'projectmoduleupdate' detailprojectmodule.id %}"><i class="fas fa-edit mr-2"></i>Edit</a>
                </div>
              </div>
            </div>
            {% comment %} <div class="col-xl-4 col-md-6">
              <div class="card card-stats">
                <!-- Card body -->
                <div class="card-body">
                  <div class="row">
                    <div class="col">
                      <h5 class="card-title text-uppercase text-muted mb-0">Project Team</h5>
                      {% comment %} <span class="h2 font-weight-bold mb-0">924</span> {% endcomment %}
                    {% comment %} </div>
                    <div class="col-auto">
                      <div class="icon icon-shape bg-gradient-green text-white rounded-circle shadow">
                        <i class="ni ni-single-02"></i>
                      </div>
                    </div>
                  </div> {% endcomment %}
                  {% comment %} {% for t in team %}
                  
                  <p class="mt-3 mb-0 text-sm">
                    <span class="text-nowrap font-weight-bold mr-1">Developer : </span>
                    <span class="text-nowrap text-success font-weight-bold"> {{ t.user.username }} </span>
                    <br>
                    <span class="text-nowrap font-weight-bold mr-1">Email : </span>
                    <span class="text-nowrap text-success font-weight-bold"> {{ t.user.email }} </span>
                  </p>
                  
                  {% endfor %}  {% endcomment %}
                  
                </div>

                {% comment %} <div class="ms-auto text-end d-flex flex-row-reverse">
                    <a class="btn btn-link text-danger text-gradient px-3 mb-0" href="{% url 'projectdelete' projectdetail.id %}"><i class="fas fa-trash mr-2"></i>Delete</a>
                    <a class="btn btn-link text-dark px-3 mb-0" href="{% url 'projectupdate' projectdetail.id %}"><i class="fas fa-edit mr-2"></i>Edit</a>
                </div> {% endcomment %}

              </div>
            </div>
          </div>
        </div>
      </div>
    </div>



  {% include "includes/footer.html" %}

</div>

{% endblock content %}

<!-- Specific JS goes HERE --> 
{% block javascripts %}
<script src="{% static '/assets/vendor/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js' %}"></script>
{% endblock javascripts %}